# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  graphql-server:
    container_name: graphql_server
    build:
      context: ./graphql_server
      target: final
    ports:
      - ${GRAPHQL_PORT}:${GRAPHQL_PORT}
    # to connect to local mongo, can't be host network mode as mongo container not available via localhost
    environment:
      - ROCKET_DATABASES={mongodb={url=${MONGO_CONNECTION_URL}}}
      - ROCKET_PORT=${GRAPHQL_PORT}

    # this should only run once mongodb container is healthy
    depends_on:
      mongo-db:
        condition: service_healthy
        restart: true

  matchmaking-server:
    container_name: matchmaking_server
    build:
      context: ./matchmaking
      target: final
    network_mode: host
    environment:
      - ROCKET_PORT=${MATCHMAKING_PORT}
  # add depends on graphql-server

  client:
    container_name: client_server
    build:
      context: ./client
      target: final
    environment:
      NODE_ENV: production
    network_mode: host
    depends_on:
      matchmaking-server:
        condition: service_started
        restart: true
      graphql-server:
        condition: service_started
        restart: true

  mongo-db:
    image: mongo
    container_name: ${MONGO_CONTAINER_NAME}
    restart: always
    expose:
      - 27017
      # this is the port mongo container uses, as we want our other services to be able to connect to it
    volumes:
      - mongo_volume:/data/db 
      - mongo_volume:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      # if container can be pinged to, the cmd returns 1
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s


volumes:
  mongo_volume:
    name: 2p_wordle_db

networks:
  default:
    name: wordle-network
    driver: bridge