services:
  graphql-server:
    container_name: graphql_server
    build:
      context: ./graphql_server
      target: final
    ports:
      - 10000:${GRAPHQL_PORT}
    # to connect to local mongo, can't be host network mode as mongo container not available via localhost
    environment:
      - ROCKET_DATABASES={mongodb={url=${MONGO_CONNECTION_URL}}}
      - ROCKET_PORT=${GRAPHQL_PORT}

    # this should only run once mongodb container is healthy
    depends_on:
      mongo-db:
        condition: service_healthy
        restart: true
      
  matchmaking-server:
    container_name: matchmaking_server
    build:
      context: ./matchmaking
      target: final
    ports:
      - ${MATCHMAKING_PORT}:${MATCHMAKING_PORT}   # for development purposes we forward ports
    environment:
      - ROCKET_PORT=${MATCHMAKING_PORT}
    # depends on graphql-server
    depends_on:
      - graphql-server

  word-server:
    container_name: word_server
    build:
      context: ./word
    environment:
      - WORD_PORT=${WORD_PORT}
      - MONGO_CONNECTION_URL=${MONGO_CONNECTION_URL}  
      - USE_COMPOSE=true
    ports:
      - ${WORD_PORT}:${WORD_PORT}     # for development purposes we forward ports
    # depends on mongo
    depends_on:
      mongo-db:
        condition: service_healthy
        restart: true

  client:
    container_name: client
    build:
      context: ./client
      target: final
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    depends_on:
      - graphql-server
      - matchmaking-server
      - word-server
      - rabbitmq

  mongo-db:
    image: mongo:7.0
    container_name: ${MONGO_CONTAINER_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    restart: unless-stopped
    # ports:
    #   - "27017:27017"  # Expose MongoDB to the host machine for development purposes
    expose:
      - 27017
      # this is the port mongo container uses, as we want our other services to be able to connect to it
      # but we don't need to expose it to the host machine, we use 'expose' instead of 'ports'
    volumes:
      - mongo_volume:/data/db 
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      # if container can be pinged to, the cmd returns 0 (success code for a terminal command)
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 1m30s

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_BASICAUTH_USERNAME: ME_ADMIN
      ME_CONFIG_BASICAUTH_PASSWORD: ME_PASSWORD
     # these variables are for the basic auth login to mongo-express, not to be confused
    ports:
      - "8081:8081"
    depends_on:
      - mongo-db

  rabbitmq:
    container_name: rabbitmq
    build: 
      context: ./rabbitmq
    ports:
      - "15672:15672"   # Management/monitor UI
      - "15674:15674"   # STOMP over WebSocket for development purposes 
      - "15675:15675"   # MQTT over WebSocket for development purposes
      - "61613:61613"   # STOMP over TCP for development purposes
    expose:
      - 15675         # MQTT over WebSocket for other services to connect to
      - 15674         # STOMP over WebSocket for other services to connect to 
      - 61613         # STOMP over TCP for other services to connect to 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      # these variables are for the management/monitor UI login
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running", "&&", "rabbitmq-diagnostics", "-q", "check_local_alarms"]
        # if both checks succeed, the exit code will be 0
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  mongo_volume:
    name: 2p_wordle_db

networks:
  default:
    name: wordle-network
    driver: bridge