name: Rust

on:
  push:
    paths:
      - graphql_server/**
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # - name: Set up Rust
    #   uses: actions-rs/toolchain@v1
    #   with:
    #     toolchain: stable
    #     override: true

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('backend/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache cargo git index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-git-${{ hashFiles('backend/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-git-

    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: graphql_server/target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('backend/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-

    - name: Build graphql_server
      run: cargo build --verbose
      working-directory: graphql_server

    - name: Run tests in graphql_server
      run: cargo test --verbose
      working-directory: graphql_server
